[package]
name = "infers"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
cudarc = { version = "0.18.1", features = [
  "cuda-version-from-build-system",
], optional = true }
num-traits = "0.2.19"
prost = "0.14.1"
prost-types = "0.14.1"
rand = "0.9.2"
rand_distr = "0.5.1"

[dev-dependencies]
criterion = "0.8.0"

[build-dependencies]
prost-build = "0.14.1"

[features]
default = []
cuda = ["cudarc"]

[[bench]]
name = "tensor_bench"
harness = false
